version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file: .env
  cache:
    image: redis
    ports:
      - '6379:6379'
  web:
    build: .
    volumes:
      - ./:/code
    ports:
      - "5000:5000"
    depends_on:
      - db
      - cache
    env_file: .env
